package teleger;


/**
* teleger/ClientInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Friday, April 15, 2016 7:26:50 PM CEST
*/

public interface ClientInterfaceOperations 
{
  void notifyConnection (teleger.SafeUser connectedUser);
  boolean receiveFriendRequest (teleger.SafeUser user);
  boolean sendMessage (String message, String type);
} // interface ClientInterfaceOperations
