package teleger;


/**
* teleger/ClientInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Monday, April 18, 2016 9:17:58 AM CEST
*/

public interface ClientInterfaceOperations 
{
  void notifyConnection (teleger.SafeUser connectedUser);
  void receiveFriendRequest (String user);
  boolean sendMessage (String message, String type);
} // interface ClientInterfaceOperations
