package teleger;


/**
* teleger/ClientInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Monday, April 18, 2016 9:17:58 AM CEST
*/

public interface ClientInterface extends ClientInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClientInterface
