package teleger;


/**
* teleger/ClientInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public interface ClientInterfaceOperations 
{
  void notifyConnection (teleger.SafeUser connectedUser);
  boolean receiveFriendRequest (teleger.SafeUser user);
  void notifyAnswerRequest (teleger.SafeUser connectedUser, boolean acceptance);
} // interface ClientInterfaceOperations
