package teleger;

/**
* teleger/SafeUserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Friday, April 15, 2016 9:47:52 PM CEST
*/

public final class SafeUserHolder implements org.omg.CORBA.portable.Streamable
{
  public teleger.SafeUser value = null;

  public SafeUserHolder ()
  {
  }

  public SafeUserHolder (teleger.SafeUser initialValue)
  {
    value = initialValue;
  }

  @Override
public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = teleger.SafeUserHelper.read (i);
  }

  @Override
public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    teleger.SafeUserHelper.write (o, value);
  }

  @Override
public org.omg.CORBA.TypeCode _type ()
  {
    return teleger.SafeUserHelper.type ();
  }

}
