package teleger;


/**
* teleger/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Monday, April 18, 2016 9:17:58 AM CEST
*/

public interface ServerInterfaceOperations 
{
  boolean register (teleger.User userData);
  teleger.SafeUser[] logIn (String userId, String userPassword, teleger.ClientInterface client);
  boolean logOut (String userId, String userPassword);
  boolean unRegister (String userId, String userPassword);
  teleger.SafeUser[] searchNewFriends (String name);
  void sendRequestForFriend (teleger.SafeUser user, String friend);
  void notifyAnswerRequest (String connectedUser, String pass, String friend, boolean acceptance);
  boolean changePassword (String old, String _new, String user);
} // interface ServerInterfaceOperations
