package teleger;


/**
* teleger/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public interface ServerInterfaceOperations 
{
  boolean register (teleger.User userData);
  teleger.SafeUser[] logIn (String userId, String userPassword, String ip, teleger.ClientInterface client);
  boolean logOut (String userId, String userPassword);
  teleger.SafeUser[] searchNewFriends (String name);
  void sendRequestForFriend (teleger.SafeUser user, teleger.SafeUser friend);
} // interface ServerInterfaceOperations
