package teleger;


/**
* teleger/userFriendsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public final class userFriendsHolder implements org.omg.CORBA.portable.Streamable
{
  public teleger.SafeUser value[] = null;

  public userFriendsHolder ()
  {
  }

  public userFriendsHolder (teleger.SafeUser[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = teleger.userFriendsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    teleger.userFriendsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return teleger.userFriendsHelper.type ();
  }

}
