package teleger;

/**
* teleger/UserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public final class UserHolder implements org.omg.CORBA.portable.Streamable
{
  public teleger.User value = null;

  public UserHolder ()
  {
  }

  public UserHolder (teleger.User initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = teleger.UserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    teleger.UserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return teleger.UserHelper.type ();
  }

}
