package teleger;

/**
* teleger/ClientInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public final class ClientInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public teleger.ClientInterface value = null;

  public ClientInterfaceHolder ()
  {
  }

  public ClientInterfaceHolder (teleger.ClientInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = teleger.ClientInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    teleger.ClientInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return teleger.ClientInterfaceHelper.type ();
  }

}
