package teleger;


/**
* teleger/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from teleger.idl
* Sunday, April 3, 2016 7:39:38 PM CEST
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
